FROM node:18-alpine

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./tsconfig.json ./
COPY ./queue/index.mts ./queue/queue.mts ./

RUN npm install

CMD ["npm", "run", "queue:docker"]